version: "3"
services:
  backend:
    restart: always
    container_name: discord_backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:8000
    env_file:
      - .env
    volumes:
      - shared_data:/app/output
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    restart: always
    container_name: discord_frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - ${VITE_PORT}:80
    depends_on:
      - backend

volumes:
  postgres_data:
  shared_data:
